module sound

using ..NetLogo: PrimitiveRegistry, register_primitive!, REPORTER, COMMAND,
  reporter_syntax, command_syntax,
  StringType, ListType, NumberType

# Standard General MIDI instrument names (programs 0–127).
const INSTRUMENTS = [
  "ACOUSTIC GRAND PIANO",
  "BRIGHT ACOUSTIC PIANO",
  "ELECTRIC GRAND PIANO",
  "HONKY-TONK PIANO",
  "ELECTRIC PIANO 1",
  "ELECTRIC PIANO 2",
  "HARPSICHORD",
  "CLAVI",
  "CELESTA",
  "GLOCKENSPIEL",
  "MUSIC BOX",
  "VIBRAPHONE",
  "MARIMBA",
  "XYLOPHONE",
  "TUBULAR BELLS",
  "DULCIMER",
  "DRAWBAR ORGAN",
  "PERCUSSIVE ORGAN",
  "ROCK ORGAN",
  "CHURCH ORGAN",
  "REED ORGAN",
  "ACCORDION",
  "HARMONICA",
  "TANGO ACCORDION",
  "NYLON STRING GUITAR",
  "STEEL ACOUSTIC GUITAR",
  "JAZZ ELECTRIC GUITAR",
  "CLEAN ELECTRIC GUITAR",
  "MUTED ELECTRIC GUITAR",
  "OVERDRIVEN GUITAR",
  "DISTORTION GUITAR",
  "GUITAR HARMONICS",
  "ACOUSTIC BASS",
  "FINGERED ELECTRIC BASS",
  "PICKED ELECTRIC BASS",
  "FRETLESS BASS",
  "SLAP BASS 1",
  "SLAP BASS 2",
  "SYNTH BASS 1",
  "SYNTH BASS 2",
  "VIOLIN",
  "VIOLA",
  "CELLO",
  "CONTRABASS",
  "TREMOLO STRINGS",
  "PIZZICATO STRINGS",
  "ORCHESTRAL HARP",
  "TIMPANI",
  "STRING ENSEMBLE 1",
  "STRING ENSEMBLE 2",
  "SYNTH STRINGS 1",
  "SYNTH STRINGS 2",
  "CHOIR AAHS",
  "VOICE OOHS",
  "SYNTH VOICE",
  "ORCHESTRA HIT",
  "TRUMPET",
  "TROMBONE",
  "TUBA",
  "MUTED TRUMPET",
  "FRENCH HORN",
  "BRASS SECTION",
  "SYNTH BRASS 1",
  "SYNTH BRASS 2",
  "SOPRANO SAX",
  "ALTO SAX",
  "TENOR SAX",
  "BARITONE SAX",
  "OBOE",
  "ENGLISH HORN",
  "BASSOON",
  "CLARINET",
  "PICCOLO",
  "FLUTE",
  "RECORDER",
  "PAN FLUTE",
  "BLOWN BOTTLE",
  "SHAKUHACHI",
  "WHISTLE",
  "OCARINA",
  "SQUARE WAVE",
  "SAWTOOTH WAVE",
  "CALLIOPE",
  "CHIFF",
  "CHARANG",
  "VOICE",
  "FIFTHS",
  "BASS AND LEAD",
  "NEW AGE",
  "WARM",
  "POLYSYNTH",
  "CHOIR",
  "BOWED",
  "METAL",
  "HALO",
  "SWEEP",
  "RAIN",
  "SOUNDTRACK",
  "CRYSTAL",
  "ATMOSPHERE",
  "BRIGHTNESS",
  "GOBLINS",
  "ECHOES",
  "SCI-FI",
  "SITAR",
  "BANJO",
  "SHAMISEN",
  "KOTO",
  "KALIMBA",
  "BAG PIPE",
  "FIDDLE",
  "SHANAI",
  "TINKLE BELL",
  "AGOGO",
  "STEEL DRUMS",
  "WOODBLOCK",
  "TAIKO DRUM",
  "MELODIC TOM",
  "SYNTH DRUM",
  "REVERSE CYMBAL",
  "GUITAR FRET NOISE",
  "BREATH NOISE",
  "SEASHORE",
  "BIRD TWEET",
  "TELEPHONE RING",
  "HELICOPTER",
  "APPLAUSE",
  "GUNSHOT",
]

# General MIDI percussion names (MIDI notes 35–81).
const DRUMS = [
  "ACOUSTIC BASS DRUM",
  "BASS DRUM 1",
  "SIDE STICK",
  "ACOUSTIC SNARE",
  "HAND CLAP",
  "ELECTRIC SNARE",
  "LOW FLOOR TOM",
  "CLOSED HI HAT",
  "HI FLOOR TOM",
  "PEDAL HI HAT",
  "LOW TOM",
  "OPEN HI HAT",
  "LOW MID TOM",
  "HI MID TOM",
  "CRASH CYMBAL 1",
  "HI TOM",
  "RIDE CYMBAL 1",
  "CHINESE CYMBAL",
  "RIDE BELL",
  "TAMBOURINE",
  "SPLASH CYMBAL",
  "COWBELL",
  "CRASH CYMBAL 2",
  "VIBRASLAP",
  "RIDE CYMBAL 2",
  "HI BONGO",
  "LOW BONGO",
  "MUTE HI CONGA",
  "OPEN HI CONGA",
  "LOW CONGA",
  "HI TIMBALE",
  "LOW TIMBALE",
  "HI AGOGO",
  "LOW AGOGO",
  "CABASA",
  "MARACAS",
  "SHORT WHISTLE",
  "LONG WHISTLE",
  "SHORT GUIRO",
  "LONG GUIRO",
  "CLAVES",
  "HI WOOD BLOCK",
  "LOW WOOD BLOCK",
  "MUTE CUICA",
  "OPEN CUICA",
  "MUTE TRIANGLE",
  "OPEN TRIANGLE",
]

function register_extension!(registry::PrimitiveRegistry)
  # ── Reporters ──────────────────────────────────────────────────────────
  register_primitive!(registry, "SOUND:INSTRUMENTS", REPORTER,
    reporter_syntax(ret=ListType),
    (ctx, args) -> collect(INSTRUMENTS))

  register_primitive!(registry, "SOUND:DRUMS", REPORTER,
    reporter_syntax(ret=ListType),
    (ctx, args) -> collect(DRUMS))

  # ── MIDI note commands (no-ops in headless mode) ───────────────────────
  register_primitive!(registry, "SOUND:PLAY-NOTE", COMMAND,
    command_syntax(right=[StringType, NumberType, NumberType, NumberType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:PLAY-NOTE-LATER", COMMAND,
    command_syntax(right=[NumberType, StringType, NumberType, NumberType, NumberType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:START-NOTE", COMMAND,
    command_syntax(right=[StringType, NumberType, NumberType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:STOP-NOTE", COMMAND,
    command_syntax(right=[StringType, NumberType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:STOP-INSTRUMENT", COMMAND,
    command_syntax(right=[StringType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:STOP-MUSIC", COMMAND,
    command_syntax(),
    (ctx, args) -> nothing)

  # ── Drum command ───────────────────────────────────────────────────────
  register_primitive!(registry, "SOUND:PLAY-DRUM", COMMAND,
    command_syntax(right=[StringType, NumberType]),
    (ctx, args) -> nothing)

  # ── Sound-file commands (no-ops in headless mode) ──────────────────────
  register_primitive!(registry, "SOUND:PLAY-SOUND", COMMAND,
    command_syntax(right=[StringType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:PLAY-SOUND-LATER", COMMAND,
    command_syntax(right=[StringType, NumberType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:PLAY-SOUND-AND-WAIT", COMMAND,
    command_syntax(right=[StringType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:LOOP-SOUND", COMMAND,
    command_syntax(right=[StringType]),
    (ctx, args) -> nothing)

  register_primitive!(registry, "SOUND:STOP-SOUND", COMMAND,
    command_syntax(),
    (ctx, args) -> nothing)
end

end # module sound
